# First Test with GitHub Actions
#
name: Monitoring_Test
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка исходного кода
      uses: actions/checkout@v2

    - name: Запуск скрипта
      run: echo "Hello, World!"
